export const Data = [
    { title: "3d", slug: "These Items Are Extraordinary" },
  ];

  export const Category= [
    {
      title: "woodblock sort",
      price: "15",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/81glwmnt28L.png",
      category: "Most Popular",
      para: "by info@innomaxdigital",
      threed: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/81X0rGw8sJL.png",
      category: "Most Popular",
      para: "by info@innomaxdigital",
      threed: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/61cLMLZlfGL.png",
      category: "Most Popular",
      para: "by info@innomaxdigital",
      threed: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71vUrhcAyHL.png",
      category: "Most Popular",
      para: "by info@innomaxdigital",
      threed: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/817TWEcBCJL.png",
      category: "Most Popular",
      para: "by info@innomaxdigital",
      threed: "3d",
    },
    ,
    {
      title: "woodblock sort",
      price: "15",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71YefOw7VJL.png",
      category: "Most Popular",
      para: "by info@innomaxdigital",
      threed: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71WvC01RHOL.webp",
      category: "Most Popular",
      para: "by info@innomaxdigital",
      threed: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71WvC01RHOL.webp",
      category: "Most Popular",
      para: "by info@innomaxdigital",
      threed: "3d",
    },
  
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      threed: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      threed: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      animation: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      animation: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      animation: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      animation: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      animation: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      template: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      template: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      template: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      template: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      template: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      Gui: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      Gui: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      Gui: "3d",
    },
    {
      title: "woodblock sort",
      price: "15",
      category: "Featured",
      para: "by info@innomaxdigital",
      image: "https://unitycodemarket.com/wp-content/uploads/edd/2025/01/71BVn6AxvqL.png",
      Gui: "3d",
    },
  ]; 
